<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_My Wallet</name>
   <tag></tag>
   <elementGuidId>6ec4db51-c4af-4f03-ad28-3e452511aa91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-wrapper']/div/div[2]/div/div/ul/li[3]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.active > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9b0e5b84-da41-4cf6-ab09-a8198f976b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/user/account/</value>
      <webElementGuid>0f54c0b5-7c94-40ab-b2fd-4076565d38b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>certificates</value>
      <webElementGuid>6a8df347-99bf-4c5a-90f4-67370ba4c79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Wallet</value>
      <webElementGuid>64a5590a-d609-43a7-acd2-c9028212b6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-wrapper&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3 col-xs-12 margin-bottom rmv-padding menu-bar&quot;]/div[@class=&quot;panelmenu&quot;]/ul[@class=&quot;list-unstyled side_menu hidden-xs hidden-xsm hidden-sm light-bg&quot;]/li[3]/ul[@class=&quot;sub_menu&quot;]/li[@class=&quot;active&quot;]/a[1]</value>
      <webElementGuid>c6332263-0389-4879-9448-2a3a7ebda2b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/div[2]/div/div/ul/li[3]/ul/li/a</value>
      <webElementGuid>b4b99ec5-514f-430f-878b-4abe44ac3231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'My Wallet')]</value>
      <webElementGuid>fbddec20-2931-4421-b556-2aa8888ee466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payments'])[1]/following::a[1]</value>
      <webElementGuid>8f437451-dc17-4a78-9296-ceacb95412e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return Requests'])[2]/following::a[1]</value>
      <webElementGuid>83204d16-4e6a-4412-bac3-e6ba9b29c0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Gifts'])[1]/preceding::a[1]</value>
      <webElementGuid>0b68a547-fcf0-4fbb-8193-64ce9ba3493c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My stuff'])[1]/preceding::a[2]</value>
      <webElementGuid>e2fd71f6-0704-4b3b-be6c-d377b2aaac66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My Wallet']/parent::*</value>
      <webElementGuid>cbb73aae-7d94-4af0-be4b-f48135d11b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/user/account/')])[2]</value>
      <webElementGuid>68c5aa99-1b64-4b83-ba84-8dcbcee2bf08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[3]/ul/li/a</value>
      <webElementGuid>a6bc0509-24ee-4132-a5c6-ba2c06f6b657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/user/account/' and (text() = 'My Wallet' or . = 'My Wallet')]</value>
      <webElementGuid>e3d6a1a4-0f11-4ae3-98d7-4a987788263d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
