<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter gift card number_cardPIN</name>
   <tag></tag>
   <elementGuidId>932f4b1f-7ab7-40b2-8aa2-167ae6a49e7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cardPIN']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cardPIN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>183f1a74-c1dd-4bd3-b384-7065178dff23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>9db6ae3a-2a4b-4bcb-8786-555bc5cfdef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardPIN</value>
      <webElementGuid>7e328716-aac9-4aba-80ea-1b4120888308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>73d99ef5-f099-4314-97f8-eec0df7b753d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control margin-top</value>
      <webElementGuid>27386053-77c0-4721-ac53-f62e1160b5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pin</value>
      <webElementGuid>c263f7f1-70a8-48ce-ba52-1e4c34524d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardPIN</value>
      <webElementGuid>019d982d-376a-4318-8c42-a6d0f6363765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardPIN&quot;)</value>
      <webElementGuid>a09598c8-1159-4c28-b523-ea5cd6167753</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cardPIN']</value>
      <webElementGuid>8d797d4d-2efc-4259-b1dd-930669bc8396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRedeemCoupon']/fieldset/ul/li[2]/input[3]</value>
      <webElementGuid>d4d71bc5-2563-4c55-be76-e0bec69774d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>1b092e23-27b6-48ca-87f3-874f8fc0e06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'cardPIN' and @placeholder = 'Pin' and @id = 'cardPIN']</value>
      <webElementGuid>f8317e25-adf9-4672-b6be-d3d5169c4d68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
