<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter gift card pin_submitCheckBalane</name>
   <tag></tag>
   <elementGuidId>e2735dfe-a125-431b-be69-690844c80f79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='submitCheckBalane']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submitCheckBalane</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8bea7053-6d45-4077-8c17-91b346040c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8050eff1-ca20-4896-ae74-c78df20c475a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Check Balance</value>
      <webElementGuid>281dd622-5057-44c2-9aad-8dfb4be2f638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submitCheckBalane</value>
      <webElementGuid>0ffa7eaa-a0d9-4804-a087-b84a25d0e927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm margin-top</value>
      <webElementGuid>997e09e4-4c6c-48ef-bcac-471c9565c064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitCheckBalane</value>
      <webElementGuid>7e55ade3-8564-4627-8bcf-3d3b420589c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitCheckBalane&quot;)</value>
      <webElementGuid>ed400ad8-5735-4dd1-b031-208e6f16d723</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='submitCheckBalane']</value>
      <webElementGuid>65b7abfa-432b-45eb-a0e3-bfd741402b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRedeemCoupon']/fieldset/ul/li[3]/input</value>
      <webElementGuid>32b88083-4324-42f0-aef3-dc86fdf710a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/input</value>
      <webElementGuid>019a1bd5-5e86-4177-b0aa-45a283d5802f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'submitCheckBalane' and @id = 'submitCheckBalane']</value>
      <webElementGuid>f024ea79-5796-4b12-9dd5-7f67feb0ed7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
