<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Date12345678910111213141516171819202_49f153</name>
   <tag></tag>
   <elementGuidId>284aa0c4-2d7a-48db-86e2-471c87845e21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dobDay']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dobDay</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>92d5fa71-62f1-4ce2-bc84-7bf74b43358d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>57cd9f46-0135-43a3-852a-84faa8a8937e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control  dob-valid</value>
      <webElementGuid>61677405-b5dc-4c8c-ac9c-06154f65bc35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dobDay</value>
      <webElementGuid>e619e2b6-d4f6-4aaf-a032-fdcc9ba5e478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dobDay</value>
      <webElementGuid>1789b663-9cd9-497f-ad6e-cd5eaa546b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Date12345678910111213141516171819202122232425262728293031</value>
      <webElementGuid>8b7d48a4-6dd2-4bae-9673-fce6205ce6cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dobDay&quot;)</value>
      <webElementGuid>596a6bde-d487-4417-9d9d-ff0fc2b020fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dobDay']</value>
      <webElementGuid>55da842f-445e-4985-b25d-a584f53c836e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formUserProfileEdit']/fieldset/div/div/div[4]/div/div/div/div/select</value>
      <webElementGuid>a155a337-5be0-4a88-b1bd-3261fe04276f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>d78eb873-f057-4bbf-8292-4aac0dac37a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required'])[1]/preceding::select[1]</value>
      <webElementGuid>033afb42-cc4a-4e0c-b743-220ede5361a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required'])[2]/preceding::select[2]</value>
      <webElementGuid>6035f2e4-7de6-4c0a-8644-ed0212e07c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>4703bc71-63e3-418d-aada-a0519179fb29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dobDay' and @name = 'dobDay' and (text() = 'Date12345678910111213141516171819202122232425262728293031' or . = 'Date12345678910111213141516171819202122232425262728293031')]</value>
      <webElementGuid>58a309d2-b343-4e8b-a2ae-275dd3ff7d33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
