<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter Order ID_track-order</name>
   <tag></tag>
   <elementGuidId>dd956f3f-a42a-4e62-94fa-579e6a4922e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='track-order']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#track-order</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5236a482-498d-41ae-af46-a56299f7e66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8c300e19-4e2a-4e47-b650-c68bd6ae54b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>track-order</value>
      <webElementGuid>8610b58c-4b03-4bd6-b085-0a172e4c4739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>track-order</value>
      <webElementGuid>acea0a0b-6542-4033-a2ce-85c22c30b8ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm</value>
      <webElementGuid>1c988ea2-030f-446a-af6b-ed61810117dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>trackOrder</value>
      <webElementGuid>b46a8986-eec4-4377-a3e0-e5002afa515d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>GO</value>
      <webElementGuid>efd3eb02-14d3-4fe4-a491-fd4f4ac0bc56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;track-order&quot;)</value>
      <webElementGuid>950c0d98-a506-4b14-97df-8ebd8da0871b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='track-order']</value>
      <webElementGuid>00db3585-a804-4339-b50b-ee9959ceb3eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='trackOrder']/span/span[2]/input</value>
      <webElementGuid>d67287d2-0d66-4d10-b318-2bd1ce81728d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span[2]/input</value>
      <webElementGuid>12649809-9962-44e5-9cce-aaf1d14b58f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'track-order' and @id = 'track-order' and @form = 'trackOrder']</value>
      <webElementGuid>beee77f9-0de8-43aa-9d18-aa6e992b9542</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
