<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_userLoginPassword</name>
   <tag></tag>
   <elementGuidId>2473bb59-3fff-4625-b3ce-15e113969486</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='userLoginPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#userLoginPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>886f7d9d-f204-4bff-9482-17b20e31b2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ecbfc3cb-c696-4431-8bdd-61a07cb203f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userLoginPassword</value>
      <webElementGuid>5a9d745f-aa0b-46cc-af13-1f152d241f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-input</value>
      <webElementGuid>7c96ff08-5a64-44b1-b7fb-ac9403d92d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>966cc30c-6c6e-49fc-bfcb-2ca655468f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>65876304-6a0a-49a1-8252-ba01910ab878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userLoginPassword</value>
      <webElementGuid>6a85065e-c4b0-4908-bda2-1a898c0693f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userLoginPassword&quot;)</value>
      <webElementGuid>b766ea92-a241-4446-ab23-38a24efc30b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PNG/Page_Gold  Diamond  Online Jewellery Shoppi_0b87d1/iframe_Loading_loginPopup</value>
      <webElementGuid>90fc3611-7f89-4c6e-b3b7-2e627ec34022</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='userLoginPassword']</value>
      <webElementGuid>61f1e317-4c5d-48cc-a230-86cb775565c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formLogin']/div/fieldset/ul/li[2]/input</value>
      <webElementGuid>0329ae73-3f7a-4c79-84eb-c7959bbd7d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>e67d0b46-4994-42b9-8356-7ceea3ef5d68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'userLoginPassword' and @id = 'userLoginPassword']</value>
      <webElementGuid>72649c00-99c7-49c1-a515-1155f8e825c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
