<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_userLoginEmail</name>
   <tag></tag>
   <elementGuidId>1c8ec5ed-6691-4ffa-9d01-a4e3dbbe8ee0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='userLoginEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#userLoginEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30e1613f-ff52-4b34-b200-013d510958ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9b5a7cbc-85e9-4e49-a28c-43a08f62af18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userLoginEmail</value>
      <webElementGuid>afd3d168-cec3-4085-8d45-890c64a4676c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-input</value>
      <webElementGuid>bc95dd36-3294-4dd3-aa32-f51c52debf5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e2f830d0-a4cb-47ab-b0ac-b0cf16ff58f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>851ac892-c7fc-49d9-959f-0b3fad310549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userLoginEmail</value>
      <webElementGuid>8a1a3061-6c42-4308-83cd-2e27e9298988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userLoginEmail&quot;)</value>
      <webElementGuid>75460df4-9346-4924-a49f-e2bec4e5567f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PNG/Page_Gold  Diamond  Online Jewellery Shoppi_0b87d1/iframe_Loading_loginPopup</value>
      <webElementGuid>16e304a2-73f1-46e0-b129-22f57126199d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='userLoginEmail']</value>
      <webElementGuid>6346998d-b88d-40cd-9d33-9b693880a6fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formLogin']/div/fieldset/ul/li/input</value>
      <webElementGuid>133b7c61-fcf1-44ce-9360-9b6f1c5456e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>dfe68bdf-a84e-4a20-bda1-bd27796c07de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'userLoginEmail' and @id = 'userLoginEmail']</value>
      <webElementGuid>ac58a6c3-a612-4c73-832c-055aaf4e7828</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
