<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_submitLogin</name>
   <tag></tag>
   <elementGuidId>1b5c153b-a8be-4b08-b733-0476e2c6cec6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='submit-login']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submit-login</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a657a6ef-03bf-4674-a72c-b02aefed7137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c71680dc-4d1e-4625-a218-0cc139621a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submitLogin</value>
      <webElementGuid>a0e1856d-3b52-46c5-99fe-0d88a787640b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit-login</value>
      <webElementGuid>86caa4a4-97d2-4281-8592-a3cfd307662a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validate_submit</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>4ed8b186-5bdd-4bf1-a3d0-f2f696369e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Log me in</value>
      <webElementGuid>735bdd76-dd64-4daa-b2f0-8a3b7b9b3d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-block btn btn-primary proceedBtn</value>
      <webElementGuid>ba4c7660-2fc0-440b-8f83-2ac3ac447d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit-login&quot;)</value>
      <webElementGuid>c3526160-5400-4fc0-a04e-2b1de32d61ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PNG/Page_Gold  Diamond  Online Jewellery Shoppi_0b87d1/iframe_Loading_loginPopup</value>
      <webElementGuid>51da2324-33df-43ab-9754-c7211afb418b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='submit-login']</value>
      <webElementGuid>75f2242a-f48d-4a43-8fab-53d4beb0d0db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formLogin']/div/fieldset/ul/li[3]/input</value>
      <webElementGuid>6d61dd27-2a8c-4d81-88cb-cd5c618a59b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/input</value>
      <webElementGuid>9a01c220-9c51-4473-8560-01e780377928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'submitLogin' and @id = 'submit-login']</value>
      <webElementGuid>3d52065d-9d68-4463-9ab9-24c407884f23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
