<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_My Location_locatoraid-search-form-button</name>
   <tag></tag>
   <elementGuidId>6b7b7d7a-45d4-41e2-985e-458dd80781ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='locatoraid-search-form-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#locatoraid-search-form-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c31e68e-05cd-4113-8cbc-fcc7c7413e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f550db65-6d12-49ca-9760-d120ad488f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>ae83e2c1-c71f-417b-948c-008063cd2aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>b535178c-f67a-4dce-ba75-b086c23d1f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hc-block</value>
      <webElementGuid>ca5fd683-30c9-4c06-8548-f53242c86cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>locatoraid-search-form-button</value>
      <webElementGuid>3b75365f-c131-45a1-9a8b-f4c2478712ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locatoraid-search-form-button&quot;)</value>
      <webElementGuid>356f2d14-c469-435b-b017-8108fb77a847</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='locatoraid-search-form-button']</value>
      <webElementGuid>1712978a-b652-4826-9444-005cdbf55882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='locatoraid-search-form-inputs-button']/div/div[2]/div/input</value>
      <webElementGuid>8e30b9bf-bd36-419c-a029-738043c3c64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>c2e335dc-4f27-41bf-9dcf-27c1ae228390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @title = 'Search' and @id = 'locatoraid-search-form-button']</value>
      <webElementGuid>198bd6f7-f965-48ba-b94f-b01e0c4ec056</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
