<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Store Locator_hc-search</name>
   <tag></tag>
   <elementGuidId>284b1ebb-75b7-422e-b408-8ea8cdeb0579</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='hc-search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;hc-search&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23de2b0b-20c5-42ce-a75d-695c3a2c09cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c1ebddf3-d45b-4377-af89-5f584885c5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hc-search</value>
      <webElementGuid>ad270adb-dc4e-464e-9ea8-11a3172ca7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hc-field hc-xs-block hc-block</value>
      <webElementGuid>d53074db-ae74-4a70-8b28-19d8dc778252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address or Zip Code</value>
      <webElementGuid>c1c26cd7-3631-45fb-9e60-8995155946f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locatoraid-search-form-search&quot;)/input[@class=&quot;hc-field hc-xs-block hc-block&quot;]</value>
      <webElementGuid>7ae4426d-20ab-45d3-a13c-4b708a8565d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='hc-search']</value>
      <webElementGuid>6b5ea62c-1803-41f4-98e3-7d7b373ee305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='locatoraid-search-form-search']/input</value>
      <webElementGuid>24681ff0-142e-430a-95ce-25d9c7227dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/input</value>
      <webElementGuid>5b1c8823-8696-4f1f-888a-be7911ba13ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'hc-search' and @placeholder = 'Address or Zip Code']</value>
      <webElementGuid>c010cd7f-69d3-4efa-bb38-a2b62ee63667</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
